#!/bin/bash

# Start vote server
./start_registry json/VoteServer.json

# Start mix nodes
./start_mixnode json/m1.json
./start_mixnode json/m2.json
./start_mixnode json/m3.json

# Start verifiers
./start_verifier json/v1.json
./start_verifier json/v2.json
./start_verifier json/v3.json

sleep 2
# Start simulated clients
./start_client json/VoteClient.json Clinton
./start_client json/VoteClient.json Bush
./start_client json/VoteClient.json Clinton
./start_client json/VoteClient.json Clinton
./start_client json/VoteClient.json Clinton
./start_client json/VoteClient.json Bush

